### ISSUE TITLE
Account Disabled

### ISSUE THREAD

**Issue by vaporox** [vaporox/chat#1]
Welp, I just authorized my account at https://ksoft.si and then it got disabled for violating the guidelines (See my latest messages on the discord.js server for the context why). It also seems like that has already happened before (https://support.discord.com/hc/en-us/community/posts/4408129956887)

I'm not going to create an alt account, so I thought I'll let you know over GitHub in case anyone's wondering about me being gone.

I've already sent an appeal too, but I'm not too optimistic that any human employee will ever read it, let alone enable my account again after looking at it further.

---

CC: @elektr1x @extroonie @gon20000 @officialsirh @toastersticks @togarashipepper

**Comment by vaporox** [comment]
I've already sent an appeal too, but I'm not too optimistic that any human employee will ever read it, let alone enable my account again after looking at it further

**Comment by OfficialSirH** [comment]
I will find a way to get in contact with Discord's support as quickly as
possible, I know certain contacts.

>

**Comment by OfficialSirH** [comment]
Welp, you'll have to wait for Discord Support to see your ticket after what I was told by one of the employees

**Comment by ToasterSticks** [comment]
Joe bidome

**Comment by OfficialSirH** [comment]
ffs Toast

**Comment by EleKtr1X** [comment]
damn, that sucks
hope your account isn't deleted, good luck with that

**Comment by OfficialSirH** [comment]
> damn, that sucks hope your account isn't deleted, good luck with that

they delete accounts approximately after a month

**Comment by ToasterSticks** [comment]
So your discord account got disabled for authorizing with another app?

**Comment by ToasterSticks** [comment]
I am confusion

**Comment by OfficialSirH** [comment]
exactly, it makes no sense, but that's what got his account disabled

**Comment by ToasterSticks** [comment]
a little trolling

**Comment by OfficialSirH** [comment]
I've found further details about why this issue occurs.
![image](https://user-images.githubusercontent.com/66775276/143982929-f19ab9e6-63b6-44d5-9afe-9fb36f0e7b57.png)

**Comment by vaporox** [comment]
Oh alright, that's already good to hear. In my appeal I haven't mentioned KSoft and/or the server at all, only that I tried to authorize an application and suddenly I was logged out. I guess I need to explain all that after Discord's initial reply then because I don't see a way to add it for now.

**Comment by ToasterSticks** [comment]
Crydreamstan. Vape can I suck up for you?

**Comment by extroonie** [comment]
> Oh alright, that's already good to hear. In my appeal I haven't mentioned KSoft and/or the server at all, only that I tried to authorize an application and suddenly I was logged out. I guess I need to explain all that after Discord's initial reply then because I don't see a way to add it for now.

Just keep in mind that if Discord's T&S is sending automated replies, keep bumping to get in touch with a human. Pretty sure you'll get it back.

**Comment by PrincessRavy** [comment]
Hi gamers, I've reached out to Discord staff with some more insight on this -- hopefully it can be resolved once and for all :)

**Comment by TogarashiPepper** [comment]
> I will find a way to get in contact with Discord's support as quickly as possible, I know certain contacts.
> […](#)

this sounds very ominous

**Comment by vaporox** [comment]
The mail came in tonight and Discord confirmed that I was falsely caught by their spam filter! Thanks to everyone here for helping with this ❤️

**Comment by extroonie** [comment]
> Okay so I was able to log in on my PC just fine, but then I logged in on my phone and suddenly it's disabled again. I have no idea how or why but we're back to this thread

Suggested to not leave the KSoft Discord server until there's further details on this. I guess you'll have to appeal again and repeat the process.

**Comment by vaporox** [comment]
I didn't try to leave it, simply logging in caused that again

**Comment by Gon20000** [comment]
That's pretty odd, wanna duel to forget about this?

**Comment by ToasterSticks** [comment]
Have you tried to deauthorize the ksoft app within discord?

**Comment by ToasterSticks** [comment]
Nvm you can't access it bidden

**Comment by OfficialSirH** [comment]
what the heck. Discord's anti-spam is just getting haywire

**Comment by vaporox** [comment]
I've deauthorized it but apparently that didn't help

**Comment by ToasterSticks** [comment]
👍

**Comment by ToasterSticks** [comment]
Have a

**Comment by vaporox** [comment]
Got a response pretty quickly this time, account is yet again restored 👍
